---
- name: Install apache2
  apt:
    name: "{{ apache_package }}"
    update_cache: yes # get latest version available
    state: latest 

- name: Start and enable Apache2 service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: Create index.html file
  template:
    src: /etc/ansible/index.html
    dest: /var/www/html/index.html
  ignore_errors: true
