---
- hosts: linux
  become: yes
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Start and enable Apache2 service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create index.html file
      template:
        src: /etc/ansible/index.html
        dest: /var/www/html/index.html
